doc: Update dependency regex
On Fedora 42, `poetry install` would fail with

```
  - Installing regex (2023.12.25): Failed

PEP517 build of a dependency failed

Backend subprocess exited when trying to invoke build_wheel

    | Command '['/tmp/tmp3wclsqyf/.venv/bin/python', '/home/sonny/.local/share/pipx/venvs/poetry/lib64/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py', 'build_wheel', '/tmp/tmpmxkmzy46']' returned non-zero exit status 1.
    |
    | /tmp/tmp3wclsqyf/.venv/lib/python3.13/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
    | !!
    |
    |         ********************************************************************************
    |         Please consider removing the following classifiers in favor of a SPDX license expression:
    |
    |         License :: OSI Approved :: Apache Software License
    |
    |         See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
    |         ********************************************************************************
    |
    | !!
    |   self._finalize_license_expression()
    | running bdist_wheel
    | running build
    | running build_py
    | creating build/lib.linux-x86_64-cpython-313/regex
    | copying regex_3/__init__.py -> build/lib.linux-x86_64-cpython-313/regex
    | copying regex_3/regex.py -> build/lib.linux-x86_64-cpython-313/regex
    | copying regex_3/_regex_core.py -> build/lib.linux-x86_64-cpython-313/regex
    | copying regex_3/test_regex.py -> build/lib.linux-x86_64-cpython-313/regex
    | running build_ext
    | building 'regex._regex' extension
    | creating build/temp.linux-x86_64-cpython-313/regex_3
    | gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -O3 -fPIC -I/tmp/tmp3wclsqyf/.venv/include -I/usr/include/python3.13 -c regex_3/_regex.c -o build/temp.linux-x86_64-cpython-313/regex_3/_regex.o
    | regex_3/_regex.c:50:10: fatal error: Python.h: No such file or directory
    |    50 | #include "Python.h"
    |       |          ^~~~~~~~~~
    | compilation terminated.
    | error: command '/usr/bin/gcc' failed with exit code 1

Note: This error originates from the build backend, and is likely not a problem with poetry but one of the following issues with regex (2023.12.25)

  - not supporting PEP 517 builds
  - not specifying PEP 517 build requirements correctly
  - the build requirements are incompatible with your operating system or Python version
  - the build requirements are missing system dependencies (eg: compilers, libraries, headers).

You can verify this by running pip wheel --no-cache-dir --use-pep517 "regex (==2023.12.25)".

```