Update eeprom (#702)
`pieeprom-2025-03-19.bin` does not exist anymore and releases since then
bring several benefits.

```
+ cp /usr/lib/firmware/raspberrypi/bootloader-2712/latest/pieeprom-2025-03-19.bin /tmp
cp: cannot stat '/usr/lib/firmware/raspberrypi/bootloader-2712/latest/pieeprom-2025-03-19.bin': No such file or directory
+ panic 'update and configure bootloader'
+ echo -e '\e[1;31mError: couldn'\''t update and configure bootloader\e[0m'
Error: couldn't update and configure bootloader
+ exit 1
Container raspberrypi failed with error code 1.
Error: Process completed with exit code 1.
```

Once a new RPI OS is released we can stop updating `rpi-eeprom` and rely
on what's on the base os.